# Generated by Django 2.2 on 2022-11-28 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20221015_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
