# Generated by Django 2.2 on 2022-11-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_editinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditLName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_last_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EditPassword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_password", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name="EditInfo",
            new_name="EditFName",
        ),
    ]
