# Generated by Django 2.2 on 2022-10-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infra_type',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Accessible_location',
            fields=[
                ('infraID', models.IntegerField(primary_key=True, serialize=False)),
                ('locationX', models.DecimalField(decimal_places=16, max_digits=22)),
                ('locationY', models.DecimalField(decimal_places=16, max_digits=22)),
                ('isAccessible', models.BooleanField(default=True)),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing_map.Infra_type')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationX', models.DecimalField(decimal_places=16, max_digits=22)),
                ('locationY', models.DecimalField(decimal_places=16, max_digits=22)),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing_map.Infra_type')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userID', 'locationX', 'locationY')},
            },
        ),
    ]
