# Generated by Django 2.2 on 2022-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra_type',
            name='typeName',
            field=models.CharField(max_length=20),
        ),
    ]
