# Generated by Django 2.2 on 2022-10-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_map", "0002_auto_20221015_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessible_location",
            name="locationX",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="accessible_location",
            name="locationY",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="locationX",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="locationY",
            field=models.CharField(max_length=22),
        ),
    ]
