# Generated by Django 2.2 on 2022-10-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_map', '0004_auto_20221030_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
