# Generated by Django 2.2 on 2022-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_map", "0006_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessible_location",
            name="locationX",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="accessible_location",
            name="locationY",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="locationX",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="locationY",
            field=models.CharField(max_length=22),
        ),
    ]
