# Generated by Django 2.2 on 2022-11-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_map', '0007_auto_20221031_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessible_location',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
