# Generated by Django 2.2 on 2022-11-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_map", "0008_accessible_location_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
